config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#homepage'
  get 'profile', to: 'users#show'
  get 'edit_profile', to: 'users#edit'

  get 'hunt', to: 'hunts#index'
  get 'show_hunt', to: 'hunts#show'
  get 'join_hunt', to: 'hunts#join'
  get 'next_hunt', to: 'hunts#next'
  get 'previous_hunt', to: 'hunts#previous'
  get 'find_hunts', to: 'hunts#find'
  get 'preset_query_hunt',  to: 'hunts#preset_query'

  post 'hunt', to: 'hunts#create'
  patch 'sid_update_hunt', to: 'hunts#sid_update'
  patch 'leave_hunt',to: 'hunts#leave'

  delete 'delete_hunt', to: 'hunts#destroy'
end

app/models/hunt.rb
class Hunt
  include Mongoid::Document

  field :title, type: String
  field :datetime, type: Time
  field :duration, type: Integer
  field :end_datetime, type: Time

  field :max_hunter, type: Integer
  field :full, type: Boolean, default:false
  field :platform, type: String
  field :description, type: String

  field :sid, type: String

  field :voice_chat, type: String
  field :lang, type: String
  field :mic, type: Boolean, default: false

  #Associations
  belongs_to :leader, class_name: "User", inverse_of: :hunts_as_leader
  has_and_belongs_to_many :hunters, class_name: "User", inverse_of: :hunts_joined

  #Validations
  validates :title, presence: true, length: {within: 6..50}
  validates :datetime, presence: true
  validates_inclusion_of :duration, :in => 1..24
  validates_inclusion_of :max_hunter, :in => 2..16
  validates_inclusion_of :platform, :in => %w(xbox ps4 pc)
  validates :description, length: {within: 15..500}, allow_nil: true, allow_blank: true
  validates :sid, presence: true, length: { is: 12 }, allow_nil: true
  validates :voice_chat, length: {within: 5..30}, allow_nil: true, allow_blank: true
  validates_inclusion_of :lang, :in => %w(fra eng spa deu ita pol rus jpn zho kor por ara), allow_nil: true, allow_blank: true
  validates :hunters, hunter_list: true

  #Scopes
  scope :available, -> { where(:end_datetime.gt => (Time.current + 45 * 60)) }
  scope :in_progress, -> { where(:end_datetime.gt => (Time.current + 45 * 60), :datetime.lt => (Time.current) ) }
  scope :oncoming, -> { where(:datetime.gt => (Time.current)) }
  scope :finished, -> { where(:end_datetime.lt => (Time.current)) }
  scope :sort_by_asc_datetime, -> { order_by(datetime: :asc) }
  scope :with_free_slot, -> { where(:full => false) }

  #Callbacks
  before_update :update_hunt_full, on: [:leave, :join]

  def duration= value
    write_attribute(:duration, value)
    return if self.duration.blank?
    if self.datetime.present?
      end_datetime = self.datetime + (self.duration * 60 * 60)
      write_attribute(:end_datetime, end_datetime)
    end
  end

  def lang= value
    write_attribute(:lang, value) unless self.voice_chat.blank?
  end

  def mic= value
    write_attribute(:mic, value) unless self.voice_chat.blank?
  end

  def update_hunt_full
    (self.hunters.size + 1) >= self.max_hunter ? self.full = true : self.full = false
  end
end

app/controllers/hunts_controller.rb
class HuntsController < ApplicationController

  def index
    @hunt = Hunt.new
    @hunts = initial_hunts_query
    @hunts_joined_available = current_user.hunts_joined.available.sort_by_asc_datetime
    @hunts_as_leader_available = current_user.hunts_as_leader.available.sort_by_asc_datetime
  end

  def show
    @hunt_show = Hunt.find(hunt_params[:hunt_id])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def find
    @hunts = initial_hunts_query
    @hunts = @hunts.where(platform: hunt_params[:platform]) if hunt_params[:platform].present?
    @hunts = @hunts.any_of({title: /.*#{hunt_params[:title]}.*/i}) if hunt_params[:title].present?
    @hunts = @hunts.where(:datetime.gt => (hunt_params[:datetime])) if hunt_params[:datetime].present?
    if hunt_params[:voice_chat] == "1"
      @hunts = @hunts.not.where(voice_chat: nil)
      @hunts = @hunts.where(:lang.in => [hunt_params[:lang]]) if hunt_params[:lang].present?
      @hunts = @hunts.where(mic: true) if hunt_params[:mic] == "1"
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def join
    @user = current_user
    @hunt = Hunt.find(hunt_params[:hunt_id])
    authorize @hunt

    if (@hunt.hunters.size + 1) < @hunt.max_hunter
      @hunt.hunters.push(@user)
      @hunt.update!
      redirect_to hunt_path
    else
      @hunts = initial_hunts_query
      @hunts_joined_available = current_user.hunts_joined.available.sort_by_asc_datetime
      @hunts_as_leader_available = current_user.hunts_as_leader.available.sort_by_asc_datetime
      render :index
    end
  end

  def create
    @hunt = Hunt.new(hunt_params.merge(leader: current_user))
    authorize @hunt

    if @hunt.valid?
      @hunt.save!
      redirect_to hunt_path
    else
      @hunt
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def sid_update
    @hunt = Hunt.find(hunt_params[:hunt_id])
    @hunt.sid = hunt_params[:sid]
    authorize @hunt

    if @hunt.valid?
      @hunt.update!
      redirect_to hunt_path
    else
      @hunt
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def leave
    @user = current_user
    @hunt = Hunt.find(hunt_params[:hunt_id])
    authorize @hunt

    if @hunt.hunters.include?(@user)
      @user.hunts_joined.delete(@hunt)
      @user.update!
      redirect_to hunt_path
    else
      @hunts = initial_hunts_query
      @hunts_joined_available = current_user.hunts_joined.available.sort_by_asc_datetime
      @hunts_as_leader_available = current_user.hunts_as_leader.available.sort_by_asc_datetime
      render :index
    end
  end

  def destroy
    @hunt = Hunt.find(hunt_params[:hunt_id])
    authorize @hunt

    @hunt.destroy
    redirect_to hunt_path
  end

  def preset_query
    if hunt_params[:platform].empty?
      @hunts = initial_hunts_query
    else
      @hunts = initial_hunts_query.where(platform: hunt_params[:platform])
    end

    options = buttons_params.values.first.nil? ? 'noinput' : buttons_params.values.first.downcase
    case options
    when 'reset' then
      @hunts = @hunts
    when 'in progress' then
      @hunts = @hunts.in_progress
    when 'oncoming' then
      @hunts = @hunts.oncoming
    else
      @hunts = initial_hunts_query
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def hunt_params
    params.require(:hunt).permit(:title, :datetime, :duration, :max_hunter, :description, :platform, :voice_chat, :lang, :mic, :hunt_id, :sid)
  end

  def buttons_params
    params.permit(:oncoming, :in_progress, :reset)
  end

  def initial_hunts_query
    @hunts = Hunt.available.not.where(leader: current_user).with_free_slot.sort_by_asc_datetime
    @hunts = @hunts.not.where(:hunter_ids.in => [current_user.id])
  end
end

app/views/hunts/_create_hunt.html.erb
<div id="form-container-hunt">
  <div id="hunt-create-errors"></div>
  <div class="form-padding-side">
    <p>Field with <span>*</span> must be filled</p>
    <%= form_for @hunt, as: :hunt, url: hunt_path(@hunt), method: :create, remote: true do |f| %>
      <div id="form-hunt-left">
        <div id="form-hunt-title">
          <%= f.text_field :title, placeholder: "This is the title of your hunt" %>
          <span>*</span>
        </div>
        <div id="bootstrap-datetime">
          <div class="container">
            <div class="form-row">
              <div class="col-xs-4">
                <div class="form-group">
                  <div class="input-group date" id="datetimepicker" data-target-input="nearest">
                    <%= f.text_field :datetime, class: "form-control datetimepicker-input input-sm", data: {target:"#datetimepicker"}, placeholder: "Select date" %>
                    <div class="input-group-append" data-target="#datetimepicker" data-toggle="datetimepicker">
                      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xs-1" id="no-padding-left">
                <span>*</span>
              </div>
              <div class="col-xs-4">
                <div class="form-hunt-duration">
                  <%= f.label :duration do %>
                    <%= f.select :duration, ((1..24).map {|i| [i,i] }) %>
                    <p>Hours of estimated play</p>
                    <span>*</span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div>
          <%= f.label :max_hunter do %>
            <%= f.select :max_hunter, ((2..16).map {|i| [i,i] })%>
            <p>Maximum hunter (you included)</p>
            <span>*</span>
          <% end %>
        </div>
        <div>
          <%= f.label :platform do %>
            <%= f.select :platform, ['pc','xbox', 'ps4'] %>
            <p>Select your game platform</p>
            <span>*</span>
          <% end %>
        </div>
        <div class="form-hunt-chat">
          <%= f.text_field :voice_chat, placeholder: "Link to your voice chat", id: "hunt-voice-chat" %>
          <%= f.label :lang, class: "show-hide-label" do %>
            <p>Chat language:</p>
            <%= f.select :lang, ['', 'fra', 'eng', 'spa', 'deu', 'ita', 'pol', 'rus', 'jpn', 'zho', 'kor', 'por', 'ara'] %>
          <% end %>
          <div>
            <%= f.label :mic, class: "show-hide-label" do %>
              <%= f.check_box :mic %>
              <p>Microphone compulsory</p>
            <% end %>
          </div>
        </div>

      </div>
      <div id="form-hunt-right">
        <div>
          <%= f.text_area :description, placeholder: "You can explain more about your hunt (not necessary)" %>
        </div>
      </div>
      <div>
        <%= f.button "Create Hunt", class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/hunts/_find_hunts.html.erb
<div id="form-container-hunt-finder">
  <div class="form-padding-side">
    <%= form_for :hunt, as: :get, url: find_hunts_path(@get), method: :get, remote: true do |f| %>
      <div>
        <%= f.label :platform do %>
          <%= f.select :platform, ['pc','xbox', 'ps4'] %>
          <p>Select your game platform</p>
        <% end %>
      </div>
      <div id="bootstrap-datetime-finder">
        <div class="container">
          <div class="form-row">
            <div class="col-xs-4">
              <div class="form-group">
                <div class="input-group date" id="datetimepickerfinder" data-target-input="nearest">
                  <%= f.text_field :datetime, class: "form-control datetimepicker-input input-sm", data: {target:"#datetimepickerfinder"}, placeholder: "Select date" %>
                  <div class="input-group-append" data-target="#datetimepickerfinder" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="form-hunt-title-finder"><%= f.text_field :title, placeholder: "Words contained in the title" %></div>
      <div id="form-hunt-chat-finder">
        <%= f.label :voice_chat do %>
          <%= f.check_box :voice_chat, id: "hunt-voice-chat-finder"%>
          <p>With voice chat</p>
        <% end %>
        <div class="show-hide-finder-label">
          <%= f.label :lang do %>
            <p>Language</p>
            <%= f.select :lang, ['', 'fra', 'eng', 'spa', 'deu', 'ita', 'pol', 'rus', 'jpn', 'zho', 'kor', 'por', 'ara'] %>
          <% end %>
          <%= f.label :mic do %>
            <%= f.check_box :mic%>
            <p>Microphone compulsory</p>
          <% end %>
        </div>
      </div>
      <div>
        <%= f.button "Find Hunts", class: "button" %>
      </div>
    <% end %>
  </div>
</div>

app/views/hunts/_hunts.html.erb
<% if @hunts.present? %>
  <div class="hunts-dashboard">
    <div class="hunts-buttons">
      <%= form_for :hunt, as: :get, url: preset_query_hunt_path(@get), method: :get, remote: true do |f| %>
        <%= f.select :platform, ['pc','xbox', 'ps4'] %>
        <%= submit_tag 'Reset', name: 'reset', class: "button-small" %>
        <%= submit_tag 'In progress', name: 'in_progress', class: "button-small" %>
        <%= submit_tag 'Oncoming', name: 'oncoming', class: "button-small" %>
      <% end %>
    </div>
    <div class="hunts-header">
      <div class="hunt-title">Title</div>
      <div class="hunt-date">Date</div>
      <div class="hunt-time">Start at</div>
      <div class="hunt-duration">Duration</div>
      <div class="hunt-slot">Hunters enlisted</div>
      <div class="hunt-leader">Leader</div>
      <div class="hunt-platform">Platform</div>
    </div>
    <% @hunts.each do | hunt | %>
      <%= link_to show_hunt_path(hunt: { hunt_id: hunt.id }), remote: true do %>
        <div class="hunt-display trigger-modal">
          <div class="hunt-title"><%= hunt.title %></div>
          <div class="hunt-date"><%= hunt.datetime.strftime("%a. %d/%m") %></div>
          <div class="hunt-time"><%= hunt.datetime.strftime("%Hh%M") %></div>
          <div class="hunt-duration"><%= hunt.duration %>h</div>
          <div class="hunt-slot"><%= hunt.hunters.size + 1 %>/<%= hunt.max_hunter %></div>
          <div class="hunt-leader"><%= hunt.leader.username %></div>
          <div class="hunt-platform"><%= hunt.platform %></div>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <h3>There are no avaible hunt</h3>
  <div><%= link_to "Reload", preset_query_hunt_path(hunt: {platform: ''}), class: "button-small", remote: true %></div>
<% end %>

app/views/hunts/_hunts_as_leader.html.erb
<div class="hunts-dashboard-min">
  <h2>Hunts Created</h2>
  <p>don't forget to add your session id !</p>
  <div class="hunts-header">
    <div class="hunt-sid-min">Sid</div>
    <div class="hunt-info-min">
      <div class="hunt-date-min">Date</div>
      <div class="hunt-time-min">Start at</div>
      <div class="hunt-title-min">Title</div>
    </div>
  </div>
  <div id="hunt-unique-error"></div>
  <% @hunts_as_leader_available.each do | hunt | %>
    <div class="hunt-display">
      <div class="hunt-sid-min">
        <% if hunt.sid.present? %>
          <%= hunt.sid %>
        <% else %>
          <%= form_for :hunt, as: :post, url: sid_update_hunt_path(@post), method: :patch, remote: true do |f| %>
            <%= f.button "Add", class: "button-small" %>
            <%= f.hidden_field :hunt_id, value: hunt.id %>
            <%= f.text_field :sid, placeholder: "session id" %>
          <% end %>
        <% end %>
      </div>
      <%= link_to show_hunt_path(hunt: { hunt_id: hunt.id }), remote: true do %>
        <div class="hunt-info-min trigger-modal">
          <div class="hunt-date-min"><%= hunt.datetime.strftime("%a. %d/%m") %></div>
          <div class="hunt-time-min"><%= hunt.datetime.strftime("%Hh%M") %></div>
          <div class="hunt-title-min"><%= hunt.title %></div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/hunts/_hunts_joined.html.erb
<div class="hunts-dashboard-min">
  <h2>Hunts Joined</h2>
  <div class="hunts-header">
    <div class="hunt-sid-min">Sid</div>
    <div class="hunt-info-min">
      <div class="hunt-date-min">Date</div>
      <div class="hunt-time-min">Start at</div>
      <div class="hunt-title-min">Title</div>
    </div>
  </div>
  <% @hunts_joined_available.each do | hunt | %>
    <%= link_to show_hunt_path(:hunt => { :hunt_id => hunt.id }), remote: true do %>
      <div class="hunt-display trigger-modal">
        <div class="hunt-sid-min">
          <% if hunt.sid.present? %>
            <%= hunt.sid %>
          <% else %>
            wait the sid
          <% end %>
        </div>
        <div class="hunt-info-min">
          <div class="hunt-date-min"><%= hunt.datetime.strftime("%a. %d/%m") %></div>
          <div class="hunt-time-min"><%= hunt.datetime.strftime("%Hh%M") %></div>
          <div class="hunt-title-min"><%= hunt.title %></div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/hunts/_show.html.erb
<div class="modal-background">
  <div class="modal-content">
    <div>
      <span class="modal-close-button">X</span>
    </div>
    <div>
      <p>Platform: <%= @hunt_show.platform.upcase %></p>
      <p>Title: <%= @hunt_show.title %></p>
      <p>Hunters enlisted: <%= @hunt_show.hunters.size + 1 %>/<%= @hunt_show.max_hunter %></p>
      <p>Hunt begin: <%= "#{@hunt_show.datetime.strftime("%A %d %B")} at #{@hunt_show.datetime.strftime("%Hh%M")}" %></p>
      <p>Hunt end: <%= "#{@hunt_show.end_datetime.strftime("%A %d %B")} at #{@hunt_show.end_datetime.strftime("%Hh%M")}" %></p>
      <p>Voice chat:
        <% if @hunt_show.voice_chat.present? %>
          <%= "#{@hunt_show.voice_chat} Lang: #{@hunt_show.lang} Mic: #{@hunt_show.mic}" %>
        <% else %>
          <%= "no voice chat" %>
        <% end %>
      </p>
      <% if @hunt_show.description.present? %>
          <p>Description:</p>
          <p class="padding-side"><%= @hunt_show.description %></p>
        <% else %>
          <p>Description: no description</p>
      <% end %>
    </div>
    <div>
      <p>Leader: <%= @hunt_show.leader.username %></p>
      <p>Hunters:</p>
      <% @hunt_show.hunters.each do |hunter| %>
        <p class="hunter-list"><%= hunter.username %>  </p>
      <% end %>
    </div>
    <% if policy(@hunt_show).join? %>
      <div>
        <%= link_to "Join the hunt", join_hunt_path(:hunt =>{ :hunt_id =>
        @hunt_show.id }), class: "button" %>
      </div>
    <% end %>
    <% if policy(@hunt_show).leave? %>
      <div>
        <%= link_to "Leave Hunt", leave_hunt_path(:hunt =>{ :hunt_id =>
          @hunt_show.id }), :method => :patch, class: "button-warning" %>
      </div>
    <% end %>
    <% if policy(@hunt_show).destroy? %>
      <div>
        <%= link_to "Delete", delete_hunt_path(:hunt =>{ :hunt_id =>
          @hunt_show.id }), :method => :delete, class: "button-warning" %>
      </div>
    <% end %>
  </div>
</div>

app/views/hunts/create.js.erb
$('.error-explanation').remove()
$('#hunt-create-errors').html("<%= j render(partial: 'shared/error_messages', locals: { hunt: @hunt }) %>")

app/views/hunts/find.js.erb
$('#form-container-hunt-finder').hide()
$('.hunts-dashboard').remove()
$('#hunts-dashboard-container').html("<%= j render(partial: 'hunts/hunts', locals: { hunt: @hunts }) %>")

app/views/hunts/index.html.erb
<div class="spacing-side">
  <% if @hunts_joined_available.present? %>
    <%= render "hunts_joined" %>
  <% end %>
  <% if @hunts_as_leader_available.present? %>
    <%= render "hunts_as_leader" %>
  <% end %>
</div>
<div class="section-one spacing-side spacing-small" id="hunt-selector-show">
  <div id="show-hide-form-hunt">
    <%= content_tag(:h2, fa_icon("angle-double-down", text: "Click to create your hunt", right: true)) %>
  </div>
  <%= render "create_hunt" %>
</div>
<div class="spacing-side spacing-small">
  <div id="finder-selector-show">
    <%= content_tag(:h2, fa_icon("search", text: "Search Hunts", right: true)) %>
  </div>
  <div>
    <% if @hunts.present?  %>
      <%= render "find_hunts" %>
      <div id="hunts-dashboard-container">
        <%= render "hunts" %>
      </div>
    <% else %>
      <h3>There are no avaible hunt</h3>
      <div><%= link_to "Reload", hunt_path(), class: "button-small" %></div>
    <% end %>
  </div>
</div>
<div id="modal"></div>

app/views/hunts/preset_query.js.erb
$('#form-container-hunt-finder').hide()
$('.hunts-dashboard').remove()
$('#hunts-dashboard-container').html("<%= j render(partial: 'hunts/hunts', locals: { hunt: @hunts }) %>")

app/views/hunts/show.js.erb
$('.modal-background').remove()
$('#modal').html("<%= j render(partial: 'hunts/show', locals: { hunt_show: @hunt_show }) %>")

app/views/hunts/sid_update.js.erb
$('.unique-error-explanation').remove()
$('#hunt-unique-error').html("<%= j render(partial: 'shared/unique_error_message', locals: { hunt: @hunt }) %>")